/*---------------------------------------------------------------------------------------------
 * Copyright (c) Bentley Systems, Incorporated. All rights reserved.
 * See LICENSE.md in the project root for license terms and full copyright notice.
 *--------------------------------------------------------------------------------------------*/

import { beforeEach, describe, expect, it, vi } from "vitest";
import { fireEvent, render, screen, waitFor } from "@testing-library/react";
import { userEvent } from "@testing-library/user-event";
import { FormatSetPanel } from "../../components/quantityformat/FormatSetPanel.js";

import type { FormatSet } from "@itwin/ecschema-metadata";
// Mock the useTranslation hook
vi.mock("../../useTranslation.js", () => ({
  useTranslation: () => ({
    translate: (key: string) => {
      const translations: Record<string, string> = {
        "QuantityFormat:labels.formatSetDetails": "Format Set Details",
        "QuantityFormat:labels.label": "Label",
        "QuantityFormat:labels.unitSystem": "Unit System",
        "QuantityFormat:labels.description": "Description",
        "QuantityFormat:labels.formatSetDisplayLabel": "Format set display label",
        "QuantityFormat:labels.selectUnitSystem": "Select unit system",
        "QuantityFormat:labels.formatSetDescription": "Format set description",
        "QuantityFormat:labels.selectFormatSetToView": "Select a format set to view details",
      };
      return translations[key] || key;
    },
  }),
}));

describe("FormatSetPanel", () => {
  const mockOnFormatSetChange = vi.fn();
  const user = userEvent.setup();

  // Mock format set data
  const mockFormatSet = {
    name: "TestFormatSet1",
    label: "Test Format Set 1",
    unitSystem: "metric",
  } as FormatSet;

  const mockFormatSet2 = {
    name: "AutogeneratedFormatSet",
    label: "Auto-generated Format Set",
    unitSystem: "metric",
  } as FormatSet;

  beforeEach(() => {
    vi.clearAllMocks();
  });

  describe("Empty State", () => {
    it("should render empty state when no format set is provided", () => {
      render(<FormatSetPanel />);

      expect(screen.getByText("Select a format set to view details")).toBeTruthy();
    });

    it("should render empty state with correct CSS class", () => {
      const { container } = render(<FormatSetPanel />);

      expect(container.querySelector(".quantityFormat--formatSetPanel-emptyState")).toBeTruthy();
    });
  });

  describe("Format Set Display", () => {
    it("should render format set details when format set is provided", () => {
      render(<FormatSetPanel formatSet={mockFormatSet} />);

      expect(screen.getByText("Format Set Details")).toBeTruthy();
      expect(screen.getByDisplayValue("Test Format Set 1")).toBeTruthy();
      // expect(screen.getByDisplayValue("metric")).toBeTruthy(); TODO: Re-enable when format set supports UnitSystem.
    });

    it("should render correct description based on format set name", () => {
      render(<FormatSetPanel formatSet={mockFormatSet} />);

      const descriptionTextarea = screen.getByDisplayValue(/Arizona Highway Project \(Civil\)/);
      expect(descriptionTextarea).toBeTruthy();
    });

    it("should render auto-generated description for AutogeneratedFormatSet", () => {
      render(<FormatSetPanel formatSet={mockFormatSet2} />);

      const descriptionTextarea = screen.getByDisplayValue(/Auto-generated Format Set from iModel/);
      expect(descriptionTextarea).toBeTruthy();
    });

    it("should render with correct CSS classes", () => {
      const { container } = render(<FormatSetPanel formatSet={mockFormatSet} />);

      expect(container.querySelector(".quantityFormat--formatSetPanel-container")).toBeTruthy();
      expect(container.querySelector(".quantityFormat--formatSetPanel-inputRow")).toBeTruthy();
      expect(container.querySelector(".quantityFormat--formatSetPanel-inputColumn")).toBeTruthy();
    });
  });

  describe("Form Labels and IDs", () => {
    it("should have proper form labels and IDs", () => {
      render(<FormatSetPanel formatSet={mockFormatSet} />);

      const labelInput = screen.getByLabelText("Label");
      const unitSystemSelect = screen.getByLabelText("Unit System");
      const descriptionTextarea = screen.getByLabelText("Description");

      expect(labelInput).toBeTruthy();
      expect(unitSystemSelect).toBeTruthy();
      expect(descriptionTextarea).toBeTruthy();

      expect(labelInput.getAttribute("id")).toBeTruthy();
      expect(unitSystemSelect.getAttribute("id")).toBeTruthy();
      expect(descriptionTextarea.getAttribute("id")).toBeTruthy();
    });

    it("should have correct placeholders", () => {
      render(<FormatSetPanel formatSet={mockFormatSet} />);

      expect(screen.getByPlaceholderText("Format set display label")).toBeTruthy();
      expect(screen.getByPlaceholderText("Select unit system")).toBeTruthy();
      expect(screen.getByPlaceholderText("Format set description")).toBeTruthy();
    });
  });

  describe("Editable Mode", () => {
    it("should enable inputs when editable is true", () => {
      render(<FormatSetPanel formatSet={mockFormatSet} editable={true} />);

      const labelInput = screen.getByLabelText("Label") as HTMLInputElement;
      const unitSystemSelect = screen.getByLabelText("Unit System") as HTMLInputElement;
      const descriptionTextarea = screen.getByLabelText("Description") as HTMLTextAreaElement;

      expect(labelInput.disabled).toBe(false);
      expect(unitSystemSelect.disabled).toBe(false);
      expect(descriptionTextarea.disabled).toBe(false);
    });

    it("should disable inputs when editable is false", () => {
      render(<FormatSetPanel formatSet={mockFormatSet} editable={false} />);

      const labelInput = screen.getByLabelText("Label") as HTMLInputElement;
      const unitSystemSelect = screen.getByLabelText("Unit System") as HTMLInputElement;
      const descriptionTextarea = screen.getByLabelText("Description") as HTMLTextAreaElement;

      expect(labelInput.disabled).toBe(true);
      expect(unitSystemSelect.disabled).toBe(true);
      expect(descriptionTextarea.disabled).toBe(true);
    });

    it("should call onFormatSetChange when label is changed in editable mode", async () => {
      render(
        <FormatSetPanel
          formatSet={mockFormatSet}
          editable={true}
          onFormatSetChange={mockOnFormatSetChange}
        />
      );

      const labelInput = screen.getByLabelText("Label");
      await user.clear(labelInput);
      await user.type(labelInput, "New Label");

      await waitFor(() => {
        expect(mockOnFormatSetChange).toHaveBeenCalledWith({
          ...mockFormatSet,
          label: "New Label",
        });
      });
    });

    it("should not call onFormatSetChange when not editable", async () => {
      render(
        <FormatSetPanel
          formatSet={mockFormatSet}
          editable={false}
          onFormatSetChange={mockOnFormatSetChange}
        />
      );

      const labelInput = screen.getByLabelText("Label");

      // Input should be disabled, but let's test the handler logic
      fireEvent.change(labelInput, { target: { value: "New Label" } });

      expect(mockOnFormatSetChange).not.toHaveBeenCalled();
    });
  });

  describe.skip("Unit System Selection", () => { // TODO: Re-enable once format set supports UnitSystem.
    it("should display unit system select component", () => {
      render(<FormatSetPanel formatSet={mockFormatSet} editable={true} />);

      const unitSystemSelect = screen.getByLabelText("Unit System");
      expect(unitSystemSelect).toBeTruthy();
    });

    it("should show metric as default value", () => {
      render(<FormatSetPanel formatSet={mockFormatSet} editable={true} />);

      expect(screen.getByDisplayValue("metric")).toBeTruthy();
    });
  });

  describe("Description Handling", () => {
    it("should update description when text is changed", async () => {
      render(<FormatSetPanel formatSet={mockFormatSet} editable={true} />);

      const descriptionTextarea = screen.getByLabelText("Description") as HTMLTextAreaElement;
      await user.clear(descriptionTextarea);
      await user.type(descriptionTextarea, "New description");

      expect(descriptionTextarea.value).toBe("New description");
    });

    it("should have correct number of rows for textarea", () => {
      render(<FormatSetPanel formatSet={mockFormatSet} />);

      const descriptionTextarea = screen.getByLabelText("Description");
      expect(descriptionTextarea.getAttribute("rows")).toBe("4");
    });
  });

  describe("Props Updates", () => {
    it("should update when formatSet prop changes", () => {
      const { rerender } = render(<FormatSetPanel formatSet={mockFormatSet} />);

      expect(screen.getByDisplayValue("Test Format Set 1")).toBeTruthy();

      rerender(<FormatSetPanel formatSet={mockFormatSet2} />);

      expect(screen.getByDisplayValue("Auto-generated Format Set")).toBeTruthy();
    });

    it("should clear fields when formatSet becomes undefined", () => {
      const { rerender } = render(<FormatSetPanel formatSet={mockFormatSet} />);

      expect(screen.getByDisplayValue("Test Format Set 1")).toBeTruthy();

      rerender(<FormatSetPanel formatSet={undefined} />);

      expect(screen.getByText("Select a format set to view details")).toBeTruthy();
    });
  });

  describe("CSS Classes", () => {
    it("should apply correct CSS classes to inputs", () => {
      const { container } = render(<FormatSetPanel formatSet={mockFormatSet} />);

      const inputs = container.querySelectorAll(".quantityFormat--formatSetPanel-input");
      expect(inputs.length).toBeGreaterThan(0);
    });

    it("should apply correct CSS classes to layout containers", () => {
      const { container } = render(<FormatSetPanel formatSet={mockFormatSet} />);

      expect(container.querySelector(".quantityFormat--formatSetPanel-container")).toBeTruthy();
      expect(container.querySelector(".quantityFormat--formatSetPanel-inputRow")).toBeTruthy();
      expect(container.querySelector(".quantityFormat--formatSetPanel-inputColumn")).toBeTruthy();
    });
  });

  describe("Description Examples", () => {
    it("should show TestFormatSet1 description", () => {
      const testFormatSet = { ...mockFormatSet, name: "TestFormatSet1" };
      render(<FormatSetPanel formatSet={testFormatSet} />);

      expect(screen.getByDisplayValue(/Arizona Highway Project \(Civil\)/)).toBeTruthy();
    });

    it("should show TestFormatSet2 description", () => {
      const testFormatSet = { ...mockFormatSet, name: "TestFormatSet2" };
      render(<FormatSetPanel formatSet={testFormatSet} />);

      expect(screen.getByDisplayValue(/Arizona Highway Project \(Project Manager\)/)).toBeTruthy();
    });

    it("should show TestFormatSet3 description", () => {
      const testFormatSet = { ...mockFormatSet, name: "TestFormatSet3" };
      render(<FormatSetPanel formatSet={testFormatSet} />);

      expect(screen.getByDisplayValue(/My personal format set/)).toBeTruthy();
    });

    it("should show default description for unknown format set", () => {
      const testFormatSet = { ...mockFormatSet, name: "UnknownFormatSet" };
      render(<FormatSetPanel formatSet={testFormatSet} />);

      expect(screen.getByDisplayValue(/Standard format set containing/)).toBeTruthy();
    });
  });
});
