# iTwin.js Extract API Build

name: Extract API

on:
  pull_request:
    branches:
      - master
      - stable
    paths-ignore:
      - apps/**
      - packages/archive/**
    types: [opened, synchronize, reopened, ready_for_review]

jobs:
  extract-api:
    if: '! github.event.pull_request.draft'
    runs-on: ubuntu-latest
    name: Extract API
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 9

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Extract API
        env:
          TF_BUILD: 1
        run: pnpm lage extract-api check-internal
