trigger:
  - master
  - gh-readonly-queue/master

pr:
  drafts: false
  branches:
    include:
      - master
      - tree-widget/next

variables:
  - name: NodeVersion
    value: 22.x
  - name: pnpm_config_cache
    value: $(Pipeline.Workspace)/.pnpm-store

jobs:
  - job: Build
    workspace:
      clean: all
    pool:
      vmImage: ubuntu-latest
    steps:
      - template: templates/build-steps.yaml

  - job: Validate_docs
    displayName: "Validate docs"
    workspace:
      clean: all
    pool:
      vmImage: ubuntu-latest
    steps:
      - template: templates/validate-docs-steps.yaml

  - job: Check_change_files
    displayName: "Check change files"
    workspace:
      clean: all
    pool:
      vmImage: ubuntu-latest
    steps:
      - template: templates/change-files-steps.yaml
