trigger:
  - master
  - gh-readonly-queue/master

pr:
  drafts: false
  branches:
    include:
      - master

variables:
  pnpm_config_cache: $(Pipeline.Workspace)/.pnpm-store

jobs:
  - job: Build
    condition: succeeded()
    workspace:
      clean: all

    strategy:
      matrix:
        "Windows - Node 18.16.0":
          NodeVersion: 18.16.0
          OS: windows-latest
        "Linux - Node 18.16.0":
          NodeVersion: 18.16.0
          OS: ubuntu-latest
        "Mac - Node 18.16.0":
          NodeVersion: 18.16.0
          OS: macOS-latest

    pool:
      vmImage: $(OS)

    steps:
      - template: templates/build-steps.yaml

  - job: Run_e2e_tests
    displayName: "Run e2e tests"
    condition: succeeded()
    workspace:
      clean: all

    pool:
      vmImage: ubuntu-latest

    variables:
      - group: "viewer-components-react e2e tests env"

    steps:
      - template: templates/e2e-steps.yaml

  - job: Check_change_files
    displayName: "Check change files"
    condition: succeeded()
    workspace:
      clean: all

    pool:
      vmImage: ubuntu-latest

    steps:
      - template: templates/change-files-steps.yaml
