parameters:
  - name: dev
    type: boolean
    default: false
    displayName: "Publish pre-release versions"
  - name: noPublish
    type: boolean
    default: false
    displayName: "Only bump versions without publishing"

trigger: none
pr: none

pool:
  vmImage: "ubuntu-latest"

variables:
  - group: "Caleb - iTwin GitHub Token"
  - name: REPO_URL
    value: github.com/iTwin/viewer-components-react
  - name: NodeVersion
    value: 22.x
  - name: pnpm_config_cache
    value: $(Pipeline.Workspace)/.pnpm-store

steps:
  - checkout: self
    fetchDepth: 0 # Fetch all history (required by beachball to look at history)

  - task: UseNode@1
    displayName: "Use Node $(NodeVersion)"
    inputs:
      version: "$(NodeVersion)"

  - task: Cache@2
    displayName: Cache pnpm
    inputs:
      key: 'pnpm | "$(Agent.OS)" | pnpm-lock.yaml'
      path: $(pnpm_config_cache)

  - script: |
      corepack enable
    displayName: "Enable corepack"

  - script: |
      pnpm config set store-dir $(pnpm_config_cache)
    displayName: "Setup pnpm"
    env:
      COREPACK_INTEGRITY_KEYS: 0

  - script: pnpm install --frozen-lockfile
    displayName: pnpm install

  - script: pnpm audit --registry=https://registry.npmjs.org --audit-level=high --production
    displayName: Audit

  - script: pnpm exec lage lint extract-api cover --grouped
    displayName: Build, Lint, Cover and check for unexpected API changes

  - script: |
      git config --global user.email imodeljs-admin@users.noreply.github.com
      git config --global user.name imodeljs-admin
      git remote set-url origin "https://$(GITHUBTOKEN)@$(REPO_URL)"
      pnpm run publish --message "applying package updates" --token $NPM_AUTH_TOKEN --branch $branchName $beachballConfig $publishOptions
    displayName: "Publish packages"
    env:
      NPM_AUTH_TOKEN: $(npmToken)
      branchName: ${{ replace(variables['Build.SourceBranch'], 'refs/heads/', 'origin/') }}
      ${{ if eq(parameters.dev, true) }}:
        beachballConfig: "--config beachball.config.dev.js --keep-change-files"
      ${{ if eq(parameters.noPublish, true) }}:
        publishOptions: "--no-publish"
