name: Tree-Widget performance benchmark

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - apps/performance-tests/**
      - packages/itwin/tree-widget/**

jobs:
  benchmark:
    name: 'Tree-Widget: Benchmark performance'
    runs-on: ubuntu-latest
    permissions:
      # deployments permission to deploy GitHub pages website
      deployments: write
      # contents permission to update benchmark contents in gh-pages branch
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 10.6.5

      - name: Use Node.js 22
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Build benchmark tests
        run: pnpm lage build --to vcr-performance-tests

      - name: Restore dataset from cache
        uses: actions/cache/restore@v4
        id: cache-restore
        env:
          cache-name: cache-dataset
        with:
          path: "./apps/performance-tests/datasets/*.bim"
          key: performance-test-dataset-${{ hashFiles('./apps/performance-tests/src/util/Datasets.ts') }}

      - name: Run benchmark tests
        run: pnpm benchmark:tree-widget

      - name: Save generated datasets
        uses: actions/cache/save@v4
        if: steps.cache-restore.outputs.cache-hit != 'true'
        with:
          path: "./apps/performance-tests/datasets/*.bim"
          key: performance-test-dataset-${{ hashFiles('./apps/performance-tests/src/util/Datasets.ts') }}

      - name: Store benchmark result
        uses: JonasDov/github-action-benchmark@04d30c72aa7aad091b58aacbb6c182ebb2ecb6c0
        if: ${{ github.ref == 'refs/heads/master' }}
        with:
          name: Tree-Widget benchmark
          tool: 'customSmallerIsBetter'
          output-file-path: ./apps/performance-tests/tree-widget-benchmark.json
          # Access token to deploy GitHub Pages branch
          github-token: ${{ secrets.GITHUB_TOKEN }}
          # Push and deploy GitHub pages branch automatically
          auto-push: true
