# iTwin.js Extract API Build

name: Extract API

on:
  pull_request:
    branches: [master]
    paths:
      - packages/itwin/property-grid/**
      - packages/itwin/tree-widget/**
    types: [opened, synchronize, reopened, ready_for_review]

jobs:
  extract-api:
    if: '! github.event.pull_request.draft'
    runs-on: ubuntu-latest
    name: Extract API
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 10.6.5

      - name: Use Node.js 22
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Extract API
        env:
          TF_BUILD: 1
        run: pnpm lage extract-api check-internal
