# iTwin.js Extract API Build

name: Extract API

on:
  pull_request:
    branches: [master]
    paths:
      - packages/property-grid/**
      - packages/tree-widget/**
    types: [opened, synchronize, reopened, ready_for_review]

jobs:
  extract-api:
    if: '! github.event.pull_request.draft'
    runs-on: ubuntu-latest
    name: Extract API
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd

      - name: Install pnpm
        uses: pnpm/action-setup@0e279bb959325dab635dd2c09392533439d90093

      - name: Use Node.js 24
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e
        with:
          node-version: 24.15.0
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Extract API
        env:
          TF_BUILD: 1
        run: pnpm lage extract-api check-internal
